# Generated by Django 4.2.16 on 2024-11-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realestate",
            old_name="number_of_bedroom",
            new_name="number_of_bedrooms",
        ),
    ]
